# Getting Back on Track: Predicting High School Success Early

## Introduction
Providence strives to prepare all of its students for college and career. However, the most vulnerable students are unable to achieve even basic high school success and earn their diploma.

There is a rich body of research describing the importance of successful transitions into high school and performance in students' first year in ensuring high school graduation. Providence has a powerful opportunity to use data collected prior to high school to identify students with the lowest odds of graduating[^incoming]. 

This report will outline an approach to predicting two outcomes-- ninth grade promotion and graduation-- based on inputs available even before their freshman year starts. It will also demonstrate that combining this data with student results from their first quarter in ninth grade produces an even more accurate prediction of both promotion and graduation. Based on these findings, it is believed that Providence could identify students most in need of supports right from the first day of high school enrollment. The increased predictability observed when using course performance from the first quarter in ninth grade suggests that early interventions have the potential to get students on-track and highlights the importance of a smossoth transition.

The conclusion of this report will present a plan to operationalize these predictive analytics. The plan includes the business rules utilized to calculate the predictive analytics and process maps which suggest a high-level architecture to ensure the data is available to key decision-makers like principals, teachers, and interventionists. It will also demonstrate several presentations of the data that are clear and effective at conveying the meaning behind these data. It will lay the ground work for district and school RTI professionals to begin utilizing this data to effectively intervene and ensure more students are on track. Finally, it will propose a mechanism for district and school-level tracking of readiness for high school success that can be monitored over time to determine system effectiveness.

[^incoming]: Over 95% of first-time, high school freshman in Providence attended 8th grade in the prior year in a Providence middle school.

## Methods

Both graduation and ninth grade promotion are binary outcomes. All models in this paper utilize a Generalized Linear Models (GLM) using the logistic link function[^logitfunc]. Model coefficients will be presented as odds-ratios with 95% confidence intervals. Interpretting these coefficients is straightforward. A value of 2 indicates that an increase in the dependent variable by one unit is associated with doubling the likelihood of the predicted outcome.

Competing models were compared using the following techniques. Models are directly compared based on the value of AIC and residual variance, attempting to minimize both. Nested models were tested via step-wise ANOVA performing a \\(\chi^{2}\\) test to determine whether further specification resulted in predicted values that better matches the observed distribution. When setting cutoffs for determining levels of risk, potential specfications were compared based on Type I (falsely identifying a student as being likely to be promoted or to graduate) and Type II (falsely identifying a student who is likely to be promoted or to graduate as not being on-track), with a relative focus of reducing Type I error[^type1err].

[^logitfunc]: The generalized linear model predicts an outcome \\(Y\\) via \\(g(\mu) = \beta_{0} + \beta_{1}X_{n}\\). The structural component (\\(\beta_{0} + \beta_{1}X_{n}\\)) is familiar to linear modeling that directly predicts \\(Y\\) when \\(Y\\) is normally distributed. Because our response is binary, i.e. can only take on the value \\(0\\) or \\(1\\), we have to map the structural component onto \\((0,1)\\). The function \\(g(\mu)\\) represents the link-function used to map the estimated parameter \\(\mu\\) from the structural component onto this space. The logistic or logit link function is usually represented as \\(\pi(y) = \frac{exp(\beta_{0} + \beta_{1}X_{n})}{1+exp(\beta_{0} + \beta_{1}X_{n})}\\). For additional information, please refer to [http://stats.stackexchange.com/a/30909]() which provides an excellent overview of GLMs and several popular binary link functions.

[^type1err]: By minimizing Type I error relative to Type II error there is an overidentification of students who are to receive intervention. This is preferable to not providing intervention to students who could most benefit.
